### ISSUE TITLE
unable to cast hashset to ilist exception

### ISSUE THREAD

**Issue by vigouredelaruse** [HenkKin/EntityCloner.Microsoft.EntityFrameworkCore#7]
hello - given
* ef core 7 
* dbcontext model entities using HashSet<T> on collection properties 
    * ``` ex: public ICollection<AccessControlEntry> AccessControlEntries { get; set; } = new HashSet<AccessControlEntry>();     ```
* ``` result = await ((DbContext)_context).CloneAsync<T>(i => i.Include(c => c.AccessControlEntries), primaryKey); ```

cloneasync() throws the following 
```
   at EntityCloner.Microsoft.EntityFrameworkCore.DbContextExtensions.InternalCloneCollection(DbContext source, Dictionary`2 references, Object parentEntity, Type collectionItemType, String definingNavigationName, IReadOnlyEntityType definingEntityType, IEnumerable collectionValue)
   at EntityCloner.Microsoft.EntityFrameworkCore.DbContextExtensions.ResetNavigationProperties(DbContext source, Object entity, String definingNavigationName, IReadOnlyEntityType definingEntityType, Dictionary`2 references, Object clonedEntity)
   at EntityCloner.Microsoft.EntityFrameworkCore.DbContextExtensions.InternalClone(DbContext source, Object entity, String definingNavigationName, IReadOnlyEntityType definingEntityType, Dictionary`2 references)
   at EntityCloner.Microsoft.EntityFrameworkCore.DbContextExtensions.<CloneAsync>d__3`1.MoveNext()
   at TheHorselessNewspaper.HostingModel.ContentEntities.Query.ContentCollections.ContentModelQueries`1.<Clone>d__20.MoveNext() in E:\src\horseless-core\src\entities\Model.Core.Taxa\TheHorselessNewspaper.Schemas.HostingModel\ContentEntities\Query\ContentCollections\ContentModelQueries.cs:line 589
```

please advise

**Comment by vigouredelaruse** [comment]
howdy; unfortunately i'd like to apply this functionality in a headless cms app development framework, where developers will extend the dbcontext entity model after the product is shipped; i won't be in control of how they model relationships if you see what i'm saying

i'm having some success with a fork
https://github.com/HenkKin/EntityCloner.Microsoft.EntityFrameworkCore/compare/master...vigouredelaruse:EntityCloner.Microsoft.EntityFrameworkCore:ilist-replacement

i changed all the relationships in the test set to use hashset except for one and made some changes to the collection detection and population workflow

the changes i made currently pass most of the original unit tests except for ireadonly 

unfortunately the unit tests for my own code currently clone everything except for many sided relationships; hoping to get that working today

**Comment by vigouredelaruse** [comment]
howdy - re [these ](https://github.com/HenkKin/EntityCloner.Microsoft.EntityFrameworkCore/compare/master...vigouredelaruse:EntityCloner.Microsoft.EntityFrameworkCore:ilist-replacement) commits

* apply JsonSerialization for non-owned entity graph cloning
* specializes return type instance activation 
* uses a dbcontext entity graph with mixes of hashset<> and list<> navigations
* all repository tests green

question - regarding deep graph primary key and concurrency token reset 
my own test set graph resembles entity->relation->furtherNavigation->evenDeeperInThegraph 

the ids and concurrency tokens at the root of the graph are reset but nowhere else. is that what's supported by the library? or does the library support such resets everywhere in the cloned graph?

in this line of thinking it might be useful to expose a delegate that lets consumers of the library apply customizations of the graph property reset 

reason being the graphs i want to clone need case by case customization of the cloned graph

thanks

**Comment by HenkKin** [comment]
I think it can be much simpler.

[Here my changes](https://github.com/HenkKin/EntityCloner.Microsoft.EntityFrameworkCore/compare/master...features/support-for-hashsets)

If this solves your problem, I can create a new release.

The reset is based on entity configuration and your includes. It should work in the entire (nested) graph. The idea is that only included entities are reset. Not included entities stay the same, so there id's should not be reset. Even foreign keys to not included entities must not be reset.

**Comment by vigouredelaruse** [comment]
thanks so much for looking into this. i'd hate to have to write this code from scratch

i took a look at your changes and i needed to make some further [adjustments ](https://github.com/HenkKin/EntityCloner.Microsoft.EntityFrameworkCore/compare/features/support-for-hashsets...vigouredelaruse:EntityCloner.Microsoft.EntityFrameworkCore:features/support-for-hashsets )to get both test sets to complete

the summary is based around this difference in the way navigations are discovered. without this modification i get a shallow clone
```
            var entityName = entity.GetType().Name;
            var model = source.Model.FindEntityType(entity.GetType());
            if (model != null)
            {
                IEnumerable<ISkipNavigation> skipNavigations = model.GetSkipNavigations();
```
vs this
```
          foreach (var navigation in source.FindCurrentEntityType(entity.GetType(), definingNavigationName, definingEntityType).GetNavigations())
```

* my test set dbcontext has a mix of static dbset assignments and dynamic dbset discovered entities. the below code is called during model creation
```        
public static IEnumerable<Type> RegisterAllEntities<TInterface>(this Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder, params Assembly[] assemblies)
        {
            IEnumerable<Type> types = LoadTypes<TInterface>(assemblies);
            foreach (Type type in types)
                modelBuilder.Entity(type);

            return types;
        }
```

there is currently no support for applying configurations during dynamic discovery so the model is pure convention and the dbcontext has an incomplete set of static references to entities

* unless there are api dependency issues i would like to propose multitargeting for (ef core) .net 6 + 7 at the moment since i'm trying to consume the library from a multitargeted project

my changes are rather verbose but if you like we can fold them in with a pr

thanks

**Comment by HenkKin** [comment]
I added your changes to my branch. I also changed some minor fixes.
I want to have some unittests (with many to many relations (skiprelations) which reflects these changes. I want to add them next week.

I personally never use DbSets on DbContext as properties (https://github.com/HenkKin/DataAccessClient/blob/master/DataAccessClientExample/DataLayer/ExampleDbContext.cs). I Always do it dynamically and have no problems with this library.

Are these changes working for you. Or are you missing some functionality?

**Comment by vigouredelaruse** [comment]
so, given your most recent commits to this [branch ](https://github.com/HenkKin/EntityCloner.Microsoft.EntityFrameworkCore/compare/master...features/support-for-hashsets) 
* [this ](https://dev.azure.com/electricrucible/the%20horseless%20newspaper/_git/the-horseless-core?path=/src/entities/Model.Core.Taxa/Horseless.HostingModel.SmokeTests/ContentCollection/ContentCollectionTests.cs&version=GBtask-121-ensure-dynamic-middleware-discovery&line=1731&lineEnd=1731&lineStartColumn=27&lineEndColumn=53&lineStyle=plain&_a=contents) deep clone test completes 
* i could have sworn you'd commited a multitargeted branch but i had to change the project targeting for EntityCloner.Microsoft.EntityFrameworkCore to include it in my solution

i think we've investigated the original scenario with enough rigour to advance
thanks

**Comment by HenkKin** [comment]
Multi target project is under construction. It is almost ready with unittesting. After that i want to release a New version.
